Ref/bug/save as
metagamehub/dcl-edit pull request #123
Opened 2023-02-07 16:31 UTC by MichiGandi

Fix the scene id problem on the save as dialog.

2023-02-07 16:36 UTC, MGH-Automator commented
Task linked: [CU-861m92tkm fix: save as does save duplicate guid](https://app.clickup.com/t/861m92tkm)

2023-02-08 21:56 UTC, cblech requested changes

2023-02-08 21:56 UTC, cblech commented on Assets/Scripts/EditorState/SceneManagerState.cs
> +using System.Data;
Using directive is unnecessary

2023-02-08 21:56 UTC, cblech commented on Assets/Scripts/System/SceneManagerSystem.cs
> +using UnityEditor;
Using directive is unnecessary
And will throw errors when building standalone

2023-02-08 21:56 UTC, cblech commented on Assets/Scripts/System/SceneManagerSystem.cs
> +            Guid newId = default;
Use `Guid.Empty` to be more explicit

2023-02-17 04:11 UTC, cblech requested changes
There is a different problem now. When "Saving as..." this scene to a new location
![grafik](https://user-images.githubusercontent.com/11379989/219547307-78301245-e397-4a93-b95a-b8e2d4b58097.png)
I get this scene as a result
![grafik](https://user-images.githubusercontent.com/11379989/219547270-15075d0b-f748-49f5-88d3-4421414d64bc.png)

2023-02-19 06:50 UTC, cblech approved these changes

2023-02-19 06:50 UTC, merged