gizmo tool rework
metagamehub/dcl-edit pull request #129
Opened 2023-02-17 03:34 UTC by cblech

Fixes #861m8e65n, #861m41y69, and #861m41zwt

2023-02-17 03:34 UTC, MGH-Automator commented
Task linked: [CU-861m8e65n Fix bug translation when parent of parent scaled](https://app.clickup.com/t/861m8e65n)

2023-02-17 03:34 UTC, MGH-Automator commented
Task linked: [CU-861m41y69 global and local edditing for gizmo tools](https://app.clickup.com/t/861m41y69)

2023-02-17 03:34 UTC, MGH-Automator commented
Task linked: [CU-861m41zwt Implement snapping](https://app.clickup.com/t/861m41zwt)

2023-02-17 13:00 UTC, j-eissler requested changes

2023-02-17 13:00 UTC, tcdrop commented on Assets/Scripts/EditorState/GizmoState.cs
> +        // Dependencies
This comment can be removed.

2023-02-17 13:41 UTC, MichiGandi commented
1) Drag an asset out of the Asset browser
The new object is now selected and Gizmo is visable (good)
2) Press Undo
The object is now gone, but the gizmo is still there (not good)

2023-02-17 13:45 UTC, MichiGandi commented
Should this be removed?
![grafik](https://user-images.githubusercontent.com/49912665/219670562-cdf8b849-1c5a-4be3-a7a4-0d1119f804dc.png)

2023-02-17 13:50 UTC, MichiGandi commented
I could not find out how to use global mode Gizmos.

2023-02-17 13:59 UTC, j-eissler commented
When translating an object with snapping enabled the position doesn't snap correctly.

Test values: 
Gizmo tool does snap: 1
Gizmo tool translate snapping: 1
Object starting position: 0,0,16.4

Expected result: The object should snap to z-coordinate 15,14,13,12 etc.
Actual result: The object snaps to z-coordinate 15.5999, 12.3999 etc.

2023-02-19 04:03 UTC, cblech commented
> 1. Drag an asset out of the Asset browser
>        The new object is now selected and Gizmo is visable (good)
> 
>     2. Press Undo
>        The object is now gone, but the gizmo is still there (not good)

This is a problem with the asset browser and should be fixed in a separate PR

2023-02-19 22:59 UTC, merged