Scenes as assets
metagamehub/dcl-edit pull request #130
Opened 2023-02-17 11:00 UTC by j-eissler

#863fw7zzt

Scenes are displayed in the asset browser. They can be dragged and dropped or added to an existing entity via a scene component.

2023-02-17 11:00 UTC, MGH-Automator commented
Task linked: [CU-863fw7zzt Display scenes in asset browser](https://app.clickup.com/t/863fw7zzt)

2023-02-19 08:02 UTC, cblech requested changes

2023-02-19 08:02 UTC, cblech commented on Assets/Scripts/Command/AddAssetToScene.cs
> +            editorEvents.InvokeHierarchyChangedEvent();
When undoing, you also need to undo the selection state

2023-02-19 08:02 UTC, cblech commented on Assets/Scripts/SceneState/DclSceneComponent.cs
> +                new DclComponentProperty.PropertyDefinition("scene", DclComponentProperty.PropertyType.Asset, Guid.Empty));
This makes previews saves incompatible. Please convert scenes before loading

2023-02-20 21:55 UTC, j-eissler commented on Assets/Scripts/Command/AddAssetToScene.cs
> +            editorEvents.InvokeHierarchyChangedEvent();
The previous selection is now properly saved and gets restored when the command is undone.

2023-02-20 21:57 UTC, j-eissler commented on Assets/Scripts/SceneState/DclSceneComponent.cs
> +                new DclComponentProperty.PropertyDefinition("scene", DclComponentProperty.PropertyType.Asset, Guid.Empty));
Whenever the verification of the component definition fails, it now tries to use the old definition. If the old one gets verified successfully, the scene component is converted into the new format.

2023-02-28 05:41 UTC, cblech approved these changes

2023-02-28 05:41 UTC, merged

2023-02-28 05:50 UTC, MGH-Automator commented
Task linked: [CU-861md77x9 Write a system to upgrade files](https://app.clickup.com/t/861md77x9)

2023-02-28 09:55 UTC, MGH-Automator commented
Task linked: [CU-863g2p6qe Undo - Deleting an object doesn't remove its gizmo](https://app.clickup.com/t/863g2p6qe)