Appended file extension instead of replacing
metagamehub/dcl-edit pull request #141
Opened 2023-02-21 17:58 UTC by MGHStephan

Changed the path of the asset metafile to `assetname.extension.dclasset` from `assetname.dclasset`.

2023-02-21 17:59 UTC, MGHStephan commented
I wanted to use Path.Join but that requires importing a library...

2023-02-28 06:14 UTC, MGH-Automator commented
Task linked: [CU-861mczpda .dclasset files should contain the original extension of the asset](https://app.clickup.com/t/861mczpda)

2023-02-28 06:37 UTC, cblech requested changes
This does not work for "old" assets. Please write a FileUpgrader for that.
If you need help with that, feel free to contact me

2023-03-13 16:12 UTC, cblech requested changes

2023-03-13 16:12 UTC, cblech commented on Assets/Scripts/System/FileAssetLoaderSystem.cs
> +            CheckUpgrades(Directory.GetFiles(fileSystemPath, "*.*"));
You should be able to set the filter to `"*.dclasset"`. That way, you can remove the test for `.dclasset` in [line 225](#diff-3264eb4ef2e37c77f1ddc226dc3a48110b11b3e6b172dcbdd7305b5a3f9b3a9aR225)

2023-03-14 13:23 UTC, MGHStephan commented on Assets/Scripts/System/FileAssetLoaderSystem.cs
> +            CheckUpgrades(Directory.GetFiles(fileSystemPath, "*.*"));
true

2023-03-17 17:55 UTC, cblech approved these changes

2023-03-17 17:55 UTC, merged