rotating small coords lines on camera postion
metagamehub/dcl-edit pull request #148
Opened 2023-02-28 15:47 UTC by Alonsso

2023-03-03 05:28 UTC, cblech commented
The handles should not rotate freely to face the camera. Instead, each should be in one of four states. Take inspiration from how it is done in old dlc-edit

https://user-images.githubusercontent.com/11379989/222638918-34b07711-50d0-4f08-95a7-f317d4d12a18.mp4

2023-04-05 19:34 UTC, cblech requested changes

2023-04-05 19:34 UTC, cblech commented on Assets/Scripts/Visuals/GizmoSizeVisuals.cs
> +        private CameraState cameraState;
Is this needed?

2023-04-06 16:43 UTC, Alonsso commented on Assets/Scripts/Visuals/GizmoSizeVisuals.cs
> +        private CameraState cameraState;
I use it to obtain camera position values

2023-04-06 18:22 UTC, cblech commented on Assets/Scripts/Visuals/GizmoSizeVisuals.cs
> +        private CameraState cameraState;
But you are not using it in this file. Only in the LineRotator. And there you are injecting it separately [(here)](https://github.com/metagamehub/dcl-edit/pull/148/files#diff-3b8d109d316abe060bcf0fc6892f8298ddd7affbfec394174038cf91fad82075R24)

2023-04-06 19:01 UTC, alonss0 commented on Assets/Scripts/Visuals/GizmoSizeVisuals.cs
> +        private CameraState cameraState;
Oh yes, I'm sorry, I'm going to fix it.

2023-04-07 19:50 UTC, cblech approved these changes

2023-04-07 19:50 UTC, merged