Added JsonSettingsSaver
metagamehub/dcl-edit pull request #185
Opened 2023-05-12 23:41 UTC by cblech

The last opened scene is now saved with a JsonSettingsSaver on the Project level

2023-05-14 10:52 UTC, j-eissler requested changes

2023-05-14 10:52 UTC, j-eissler commented on Assets/Scripts/System/SettingsSystem.cs
> +                    var stream = File.Open(settingsPath, FileMode.OpenOrCreate, FileAccess.Read);
Encapsulate file system interaction with try catch

2023-05-14 10:52 UTC, j-eissler commented on Assets/Scripts/System/SettingsSystem.cs
> +                    var fileStream = File.Open(settingsPath, FileMode.OpenOrCreate, FileAccess.Read);
Use try catch here aswell

2023-05-19 17:48 UTC, MGH-Automator commented
Task linked: [CU-863g5ewph LastOpenedScene setting should be saved on project level, not on user level](https://app.clickup.com/t/863g5ewph)

2023-05-31 19:21 UTC, merged