Ref/feature/snackbar system
metagamehub/dcl-edit pull request #188
Opened 2023-05-14 11:33 UTC by j-eissler

#861mbhh3t

Info: renamed the branch so I had to open a new pull request

2023-05-14 11:34 UTC, MGH-Automator commented
Task linked: [CU-861mbhh3t Create Snack bar System](https://app.clickup.com/t/861mbhh3t)

2023-05-16 19:26 UTC, cblech requested changes

2023-05-16 19:26 UTC, cblech commented on Assets/Materials/BugIcon.png
Please move all Icon files into their own folder and add the license file to that folder:
https://www.apache.org/licenses/LICENSE-2.0.html
Also, as described on the linked page, add a NOTICE file, that explains, that this license only applies to the icons in this folder

2023-05-31 19:23 UTC, cblech approved these changes

2023-05-31 19:23 UTC, merged