Ref/feature/prompt system
metagamehub/dcl-edit pull request #189
Opened 2023-05-19 17:34 UTC by InamCZ

#861mqtrg5

2023-05-19 17:34 UTC, MGH-Automator commented
Task linked: [CU-861mqtrg5 Fix: Object jumps when parent changes](https://app.clickup.com/t/861mqtrg5)

2023-05-31 20:45 UTC, cblech requested changes
When using CreateDialoge and leaving the notInWindowAction empty, the dialog does not open

2023-05-31 20:45 UTC, cblech commented on Assets/Scripts/Visuals/PromptSystem.cs
> +        public Yes(System.Action action)
Please add constructors with no parameters to all actions. That way, it's easier to just check the return of CreatePrompt

2023-06-05 12:25 UTC, cblech requested changes
When a prompt is open, the background should gray out a bit, and the user should be prevented from clicking anything else than the prompt. 
If there is a `NotInWindow` Action defined, it should close when clicking next to the prompt, else it should do nothing

2023-06-13 17:56 UTC, cblech approved these changes

2023-06-13 17:56 UTC, merged