Added not Removable flag to components
metagamehub/dcl-edit pull request #199
Opened 2023-06-16 15:41 UTC by InamCZ

#861mxauj8

2023-06-16 15:41 UTC, MGH-Automator commented
Task linked: [CU-861mxauj8 Add a not removable flag into components](https://app.clickup.com/t/861mxauj8)

2023-06-23 17:19 UTC, cblech requested changes

2023-06-23 17:19 UTC, cblech commented on Assets/Scripts/System/SceneLoadSaveSystem.cs
> +            public bool isRemovable;
IsRemovable should not be saved. Rather, it should be derived from the Component Definition.

2023-07-25 18:16 UTC, cblech approved these changes

2023-07-25 18:16 UTC, merged