Draft: Ref/feature/target framerate
metagamehub/dcl-edit pull request #59
Opened 2022-11-21 14:16 UTC by MichiGandi

FrameTimeSystem is added to handle the target framereate.

The `SetApplicationTargetFramerate` function is hocked to the `onSettingsChangedEvent` event.
It may need to be called in the constructor too.
Also the `onSettingsChangedEvent` event has no invokes yet.

2022-11-23 02:30 UTC, MGH-Automator commented
Task linked: [CU-3tmdjjw cap framerate](https://app.clickup.com/t/3tmdjjw)

2022-11-23 10:14 UTC, MGH-Automator commented
Task linked: [CU-34abhtu Testing pull request linking](https://app.clickup.com/t/34abhtu)

2022-11-29 22:15 UTC, cblech requested changes
The entire Pull Request uses tabs at the start of each line. Please change it to use Spaces instead

2022-11-29 22:15 UTC, cblech commented on Assets/Scripts/System/SetupSceneSystem.cs
> +			_frameTimeSystem.SetApplicationTargetFramerate();
You should put this in the `StartUpSystem`. Because it needs to be called once for the entire application and not for every scene

2022-12-10 13:56 UTC, cblech approved these changes

2022-12-10 13:56 UTC, merged