Draft: Ref/feature/loading logo
metagamehub/dcl-edit pull request #64
Opened 2022-11-24 17:11 UTC by MichiGandi

Add a 3D dcl-edit loading logo prefab
It can not be rotated around y-Axis yet, because the color gradient is along a fixed axis in world space.
It has a diameter of 1, which can be changed upon instantiation.

![grafik](https://user-images.githubusercontent.com/49912665/203837712-0f7e87d4-e1d0-4d53-962e-035000a9c8b0.png)

2022-11-24 17:22 UTC, MGH-Automator commented
Task linked: [CU-3tmdjhf Loading Animation](https://app.clickup.com/t/3tmdjhf)

2022-11-25 16:54 UTC, cblech requested changes

2022-11-25 16:54 UTC, cblech commented on Assets/Materials/LoadingLogo/LoadingLogoCircle.mat
> +%YAML 1.1
![grafik](https://user-images.githubusercontent.com/11379989/204027372-50a9bab1-fa5b-415d-b908-5b55d9627f22.png)
![grafik](https://user-images.githubusercontent.com/11379989/204027515-13e1a863-6327-47b4-a4e1-7d93ed857728.png)
The Colors are a bit dull

2022-11-25 16:54 UTC, cblech commented on Assets/Prefabs/LoadingLogo/Animation/LoadingLogo Animation.anim
> +%YAML 1.1
For the outside ring, I liked the Bézier curve animation better than the linear one

2022-12-05 17:09 UTC, cblech approved these changes

2022-12-05 17:09 UTC, merged