Ref/bug/scale flickering
metagamehub/dcl-edit pull request #73
Opened 2022-12-12 13:11 UTC by MGHStephan

Global rotation function now returns rotation directly instead of 'wrong' matrix4x4 rotation.
At the moment the rotation gizmo is inverted when the scale in that axis is inverted as well.

2022-12-12 13:12 UTC, MGH-Automator commented
Task linked: [CU-37q5qbd Fix Bug: Scale is flickering when scaled below -1 with the scaling tool](https://app.clickup.com/t/37q5qbd)

2022-12-13 22:41 UTC, cblech requested changes

2022-12-13 22:41 UTC, cblech commented on Assets/Scripts/Tests/Documents/Neues RTF-Dokument.rtf
> +{\rtf1\adeflang1025\ansi\ansicpg1252\uc1\adeff31507\deff0\stshfdbch31505\stshfloch31506\stshfhich31506\stshfbi31507\deflang1031\deflangfe1031\themelang1031\themelangfe0\themelangcs0{\fonttbl{\f0\fbid
Please give this document a better name. 
Also, please use a different format. RTF is not very human-readable. I'd recommend using a `.md` file

2022-12-16 19:59 UTC, cblech approved these changes

2022-12-16 20:00 UTC, merged