Ref/feature/no 3d scrolling context menu
metagamehub/dcl-edit pull request #74
Opened 2022-12-12 15:10 UTC by MGHStephan

The 3D view check now also checks if the mouse is over the context menu and if so doesn't allow 3d view input.
Also renamed the private fields to match naming convention

2022-12-12 15:10 UTC, MGH-Automator commented
Task linked: [CU-37q9g4y Don't zoom scene, when you scroll while hovering over a context menu](https://app.clickup.com/t/37q9g4y)

2022-12-13 23:05 UTC, cblech commented on Assets/Scripts/Interaction/GeneralInputInteraction.cs
> +            this.sceneSaveSystem = this.sceneSaveSystem;
The second `this.` should not be there

2022-12-13 23:10 UTC, cblech requested changes

2022-12-13 23:10 UTC, cblech commented on Assets/Scripts/Interaction/GeneralInputInteraction.cs
> +            this.sceneSaveSystem = this.sceneSaveSystem;
The second `this.` should not be there

2022-12-13 23:29 UTC, MGHStephan commented
That would have been troublesome if left unnoticed, sorry. Should be fixed now

2022-12-16 20:06 UTC, cblech approved these changes

2022-12-16 20:06 UTC, merged