Ref/feature/menu bar system
metagamehub/dcl-edit pull request #79
Opened 2022-12-19 12:20 UTC by MichiGandi

Add a "menu bar system".

Using the ui builder.

2022-12-19 12:23 UTC, MGH-Automator commented
Task linked: [CU-34g4tn4 Make menu bar system](https://app.clickup.com/t/34g4tn4)

2022-12-20 04:29 UTC, cblech requested changes

2022-12-20 04:29 UTC, cblech commented on Assets/Scripts/System/MenuBarSystem.cs
> +        public void AddMenuItem(string path, UnityAction onClick, int position = -1)
Please add documentation on how this method works

2022-12-20 04:29 UTC, cblech commented on Assets/Scripts/System/MenuBarSystem.cs
> +        public void DebugCreateExampleMenu()
Remove testing code.
Or better yet, move it into a unit test

2022-12-20 04:29 UTC, cblech commented on Assets/Prefabs/UIDesign/Atoms/Scripts/MenuBarButton.cs
> +using System.Collections;
This script should be placed under `Scripts/Visuals/UiHandlers` with the postfix `Handler`.

2022-12-20 20:40 UTC, MichiGandi commented on Assets/Scripts/System/MenuBarSystem.cs
> +        public void AddMenuItem(string path, UnityAction onClick, int position = -1)
Is added.

2022-12-20 22:25 UTC, MichiGandi commented on Assets/Scripts/System/MenuBarSystem.cs
> +        public void DebugCreateExampleMenu()
Core features are tested by unit tests now.

2022-12-21 01:22 UTC, cblech approved these changes

2022-12-21 01:36 UTC, merged