Fixed: Settings Ui Update while typing
metagamehub/dcl-edit pull request #80
Opened 2022-12-20 05:41 UTC by cblech

I was not able to reproduce the bug. I've fixed it by guessing, what the problem might have been. So, please test it.

2022-12-20 05:42 UTC, MGH-Automator commented
Task linked: [CU-388e2zk Fix: Settigs visuals update while editing text](https://app.clickup.com/t/388e2zk)

2023-01-07 22:21 UTC, j-eissler approved these changes

2023-01-07 22:52 UTC, MichiGandi requested changes
Think you want to change that.

2023-01-07 22:52 UTC, MichiGandi commented on Assets/Scripts/System/SettingsSystem.cs
> +            applicationTargetFrameRate = new IntUserSetting(this, "Maximum frame rate", -1);
The description "Maximum frame rate" did not end up in the final state of this branch.

2023-01-10 15:09 UTC, MichiGandi approved these changes

2023-01-10 19:34 UTC, merged