Switch tool buttons escene view
metagamehub/dcl-edit pull request #84
Opened 2022-12-23 16:06 UTC by Alonsso

Left to check why the InvokeSelectionChangedEvent when CurrentMode Set unselects the entity.

2022-12-23 16:07 UTC, MGH-Automator commented
Task linked: [CU-861m41y5d Switch tool buttons in scene view](https://app.clickup.com/t/861m41y5d)

2022-12-29 16:20 UTC, Alonsso commented
In this commit c772a0fcd2f2c5e9ac02cf6355660247a507ea5e I have a blocker, not sure why the entity when click on scene button sets to null, so the method `_editorEvents.InvokeSelectionChangedEvent();` called in line 38 from `GizmoState` is hiding the gizmo, but the current mode of the gizmo is changing as spected.

2023-01-11 19:51 UTC, Alonsso commented
Hi @cblech, in this commit 1a4bbaa9ad563bd57fcca58e7ef416ee97d8d0ad I have made some changes to check when the pointer in over the buttons in the scene, I have a question: The script `MouseHoverSceneButton` is being added as a component to each button game object on the unity editor, now I need to access its `IsMouseOverGizmoModeMenu` property from the `GeneralInputInteraction`, is there a way to access the property of each one of those buttons script component?

2023-01-13 02:22 UTC, cblech commented
I'd recommend adding a list of `MouseHoverSceneButtons` into the `UnityState`. You then need to reference all Scene buttons in there. Then you can access the list via the `unityState` in `GeneralInputInteraction`

2023-01-17 09:06 UTC, cblech requested changes

2023-01-17 09:06 UTC, cblech commented on Assets/Scenes/editor.unity
> +--- !u!1 &18110688
Please apply the `GizmoModeMenu` to the `SceneTab` prefab

2023-01-17 09:06 UTC, cblech commented on Assets/Scripts/EditorState/GizmoState.cs
> +        public static UnityEvent onUpdate = new UnityEvent();
Please move this into the editor events

2023-01-21 12:00 UTC, cblech approved these changes

2023-01-21 12:01 UTC, merged