Ref/bug/fix startup sequence
metagamehub/dcl-edit pull request #89
Opened 2023-01-08 22:49 UTC by MGHStephan

The scene manager now checks if there is a dcl project and if so, continues to check for beta, alpha or no dcl-edit projects inside the dcl project folder. If a alpha or beta project is found, and there is no existing directory state, the scene's version gets written into a new scene directory state. If no dcl-edit project exists, a new scene directory state with a new scene is created. When getscene gets called, the version of the scene gets checked and the appropriate action (like loading with v1) gets taken.

2023-01-08 22:50 UTC, MGH-Automator commented
Task linked: [CU-861m3uevp Fix startup sequence](https://app.clickup.com/t/861m3uevp)

2023-01-10 20:11 UTC, cblech requested changes

2023-01-10 20:11 UTC, cblech commented on Assets/Scripts/System/SceneLoadSaveSystem.cs
> +            CheckVersionSystem checkVersionSystem,
This is not used

2023-01-10 20:11 UTC, cblech commented on Assets/Scripts/EditorState/SceneDirectoryState.cs
> +        public SceneDirectoryState(string directoryPath, Guid id, DclEditVersion dclEditVersion)
Maybe put `DclEditVersion.Beta` as default value into `dclEditVersion`

2023-01-10 20:11 UTC, cblech commented on Assets/Scripts/Installers/DclEditorInstaller.cs
>      [SerializeField]
Line 15: _loadSceneFromVersion1 is not used anymore

2023-01-13 02:04 UTC, cblech approved these changes

2023-01-13 02:04 UTC, merged